"""empty message

Revision ID: a031763cd78b
Revises: 2807edd385a2
Create Date: 2022-02-24 14:34:25.416603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a031763cd78b'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=False),
    sa.Column('cif', sa.String(length=9), nullable=False),
    sa.Column('description', sa.String(length=280), nullable=True),
    sa.Column('address', sa.String(length=70), nullable=True),
    sa.Column('province', sa.Integer(), nullable=True),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('external_url', sa.String(length=120), nullable=True),
    sa.Column('logo_url', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cif')
    )
    op.add_column('user', sa.Column('nif', sa.String(length=9), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=70), nullable=False))
    op.add_column('user', sa.Column('phone', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('image_url', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('company_id', sa.Integer(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.create_unique_constraint(None, 'user', ['nif'])
    op.create_foreign_key(None, 'user', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'password',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('user', 'company_id')
    op.drop_column('user', 'image_url')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'name')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'nif')
    op.drop_table('company')
    # ### end Alembic commands ###
